### ISSUE TITLE
Failed to compile with kernel 5.6.19

### ISSUE THREAD

**Issue by MatheusNtg** [luainkernel/lunatik#18]
Trying to compiling Lunatik with kernel 5.6.19 gives me the following message:
```
make: Entering directory '/usr/lib/modules/5.6.19-2-MANJARO/build'
  CC [M]  /home/matheus/gsoc/lunatik/lua/lapi.o
In file included from /home/matheus/gsoc/lunatik/lua/lua.h:18,
                 from /home/matheus/gsoc/lunatik/lua/lapi.c:18:
/home/matheus/gsoc/lunatik/lua/luaconf.h: In function ‘time’:
/home/matheus/gsoc/lunatik/lua/luaconf.h:846:19: error: storage size of ‘t’ isn’t known
  846 |   struct timespec t;
      |                   ^
/home/matheus/gsoc/lunatik/lua/luaconf.h:848:3: error: implicit declaration of function ‘getnstimeofday’ [-Werror=implicit-function-declaration]
  848 |   getnstimeofday(&t);
      |   ^~~~~~~~~~~~~~
/home/matheus/gsoc/lunatik/lua/luaconf.h:846:19: warning: unused variable ‘t’ [-Wunused-variable]
  846 |   struct timespec t;
      |                   ^
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:268: /home/matheus/gsoc/lunatik/lua/lapi.o] Error 1
make: *** [Makefile:1695: /home/matheus/gsoc/lunatik] Error 2
make: Leaving directory '/usr/lib/modules/5.6.19-2-MANJARO/build'
```

I think that this error is caused due a new way to handle with time implemented in kernel 5.6 ahead
